mbank/mbank/http_face/urls.py
from django.urls import path, re_path
from mbank.http_face import views
from django.contrib.auth.views import login, logout

app_name = 'http_face'
urlpatterns = [
    path('', views.home, name='home'),
    path('cadastre-se/', views.ClientCreateView.as_view(), name='register'),
    path('entrar/', login, {'template_name': 'login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'http_face:home'}, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/criar-conta/',
        views.creating_account, name='add_account'),
    path('dashboard/account_details/<uuid:account_uuid>/',
        views.account_details, name='account_details'),
]

mbank/mbank/urls.py
from django.contrib import admin
from django.urls import path, include
# from mbank import http_face

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('create-client/', ClientCreateView.as_view(), name='create_client')
    path('', include('mbank.http_face.urls', namespace='http_face')),
]

mbank/mbank/client/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


class ClientModel(AbstractUser):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    is_company = models.BooleanField('Empresarial?', blank=True, default=False)

mbank/mbank/domain/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
import uuid


class EventModel(models.Model):
    client_uuid = models.UUIDField()
    account_uuid = models.UUIDField()
    event_type = models.CharField(max_length=20)
    body = JSONField()
    version = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

mbank/mbank/http_face/models.py
from django.db import models

# Create your models here.

mbank/mbank/client/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import ClientModel
from django import forms
from django.utils.translation import gettext_lazy as _


class CreateClientForm(UserCreationForm):

    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = ClientModel
        fields = ("username", "email", "first_name", "last_name", "is_company")

mbank/mbank/domain/forms.py
from django import forms
from mbank.domain.value_object import AccountNumber, InvalidAccountNumber


class CreateAccountForm(forms.Form):
    account_number = forms.CharField()

    def clean_account_number(self):
        account_number = ''
        try:
            account_number = AccountNumber(self.cleaned_data['account_number'])
        except InvalidAccountNumber:
            raise forms.ValidationError("Numero de Conta inválido. Siga o padrão '00-000' !")

class TransactionForm(forms.Form):
    T_CHOICES = (
        (True, 'Deposito'),
        (False, 'Retirar'),
    )
    transction_type = forms.ChoiceField(choices=T_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control custom-select'})
    )
    amount = forms.FloatField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))

mbank/mbank/http_face/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.forms.forms import ValidationError
from basehelp.exceptions import InvalidInputsException
from mbank.client.domain_service import ClientCreateService
from mbank.client.forms import CreateClientForm
# from mbank.client.use_case import ClientUseCase
from mbank.domain.use_case import AccountUseCase
from mbank.domain.repository import DomainRepo
from mbank.domain.forms import CreateAccountForm, TransactionForm
from mbank.domain.domain_service import CreateAccountService



class ClientCreateView(View):

    template_name = "register.html"

    def get(self, request, *args, **kwargs):

        create_client_form = CreateClientForm()
        context = {
            'form': create_client_form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        email = request.POST.get("email")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        is_company = request.POST.get("is_company")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")

        client_create_service = ClientCreateService()

        try:
            client_create_service.run(
                username,
                email,
                first_name,
                last_name,
                is_company,
                password1,
                password2,
            )
            redirect('http_face:home')
        except InvalidInputsException:
            context = {
                'form': client_create_service.get_form()
            }

        return render(request, self.template_name, context)

def home(request):
    template_name = 'index.html'
    return render(request, template_name)

@login_required
def dashboard(request):
    account_use_case = AccountUseCase(DomainRepo())
    context = {}
    context['accounts'] = account_use_case.find_all_client_accounts(request.user)
    return render(request, 'dashboard.html', context)


@login_required
def account_details(request, account_uuid):
    repo = DomainRepo()
    account_use_case = AccountUseCase(repo)
    account = account_use_case.find_account_by_uuid(account_uuid)

    if account.get_client_uuid() != request.user.uuid:
        redirect('http_face:dashboard')

    context = {
        'accounts': account_use_case.find_all_client_accounts(request.user),
        'account': account,
        'transactions': account.get_transactions_events()
    }

    form = TransactionForm(request.POST or None)
    if form.is_valid():
        """
        django tem uma falha ao retornar valores de choice_field
        retornando os todos os valores como string, dificultando a comparação
        convertendo a string para o tipo desejado, como float(form.data.get('amount'))
        ou 
        import json
        json.loads(form.data.get('field'))
        
        lembrando que a função json.loads() produz erro ao converter a string "True",
        porem pode ser usando numa string "True".lower()
        """

        if form.data.get('transction_type') == 'True':
            account.deposit(float(form.data.get('amount')))
        elif form.data.get('transction_type') == 'False':
            account.withdraw(float(form.data.get('amount')))
        repo.update(account)
        context['transactions'] = account.get_transactions_events()
    context['form'] = form
    print(context)
    return render(request, 'account_details.html', context)


# @login_required
# def snapshot(request, account_id):
#     account = get_object_or_404(Account, id=account_id)
#     account.takeSnapshot()
#     return redirect('presentation:dashboard')


@login_required
def creating_account(request):
    form = CreateAccountForm(request.POST or None)
    context = {'form':form}
    account_use_case = AccountUseCase(DomainRepo())

    if request.method == 'POST':
        create_account_service = CreateAccountService()
        try:
            account_number = form.data['account_number']
            create_account_service.run(request.user.uuid, account_number)
            redirect('http_face:dashboard')
        except ValidationError:
            context['form'] = create_account_service.get_form()
    context['accounts'] = account_use_case.find_all_client_accounts(request.user)

    return render(request, 'creating_account.html', context)

mbank/mbank/http_face/templates/account_details.html
{% extends 'dashboard.html' %}

{% block content %}
<style type="text/css">
  #id_transction_type {
    display: inline-block;
    max-width: 100%;
    height: calc(2.25rem + 2px);
    padding: .375rem 1.75rem .375rem .75rem;
    line-height: 1.5;
    color: #495057;
    vertical-align: middle;
    background: #fff url(data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' v…'0 0 4 5'%3E%3Cpath fill='%23333' d='M2 0L0 2h4zm0 5L0 3h4z'/%3E%3C/svg%3E) no-repeat right .75rem center;
    background-size: 8px 10px;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
  }

</style>
<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          Dashboard
        </li>
        <li class="breadcrumb-item">
          Detalhes {{account.get_account_number}}
        </li>
      </ol>
      <div class="row">
        <div class="container">
          <div class="card mb-3">
            <div class="card-header">
            <i class="fa fa-table"></i> Histórico de Transações

            <!-- Botão à Direita -->
            <div class="pull-right">
                <div class="btn-group">
                  <a class="btn btn-info btn-xs" href="" role="button">Snapshot</a>
                </div>
            </div>

          </div>

            <div class="card-body">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Data</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Valor</th>
                  </tr>
                </thead>
                <tbody>
                {% for item in transactions %}
                  <tr>
                    <td>{{ item.get_created_at }}</td>
                      <td>
                        {{item.get_desc}}</td>
                        <td>
                          <i class="fa fa-plus" aria-hidden="true"></i>
                          R$ {{ item.get_amount }}</td>

                  </tr>
                {% endfor %}
                <tr>
                    <td>Hoje </td>
                    <td>Saldo</td>
                    <td>R$ {{ account.get_balance }}</td>
                </tr>
                <tr>
                    <form method="post">
                      {% csrf_token %}
                      {{ form.non_field_errors }}
                      {% for f in form %}
                        <td>{{ f }}</td>
                      {% endfor %}

                      <td><button class="btn btn-primary btn-block" type="submit">Lançar</button></td>
                    </form>
                </tr>
                </tbody>
              </table>
            </div>
            <div class="card-footer">

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- /.container-fluid-->
  <!-- /.content-wrapper-->
{% endblock %}

mbank/mbank/http_face/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <!-- ooq quero em todos -->
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="sistem bancario - portfolio">
    <meta name="author" content="moroni suaner">

    <title>MiniBank</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <style>
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    </style>
    {% block sourcefiles %}{% endblock %}

</head>

<body>
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="">MiniBank</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          {% block sidebar %}{% endblock %}
          <ul class="navbar-nav ml-auto">
          <!--
            <li class="nav-item">
              <a class="nav-link" href="#">Sobre</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Serviços</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contato</a>
            </li>
          -->
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'http_face:dashboard' %}">Painel</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'http_face:logout' %}">Sair</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'http_face:login' %}">Entrar</a>
            </li>
            {% endif %}

          </ul>
        </div>

      </div>
    </nav>
  {% block content %}



  {% endblock %}

  <div class="content-wrapper">
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% block sourcefiles_end %}{% endblock %}
  </div>
</body>

</html>

mbank/mbank/http_face/templates/creating_account.html
{% extends 'dashboard.html' %}

{% block content %}

<style>
.form-group input {
    display: block;
    width: 100%;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-image: none;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }
</style>


  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Criar Conta</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          {{ form.non_field_errors }}

          {% for field in form %}
          <div class="form-group">

            <label>{{field.label}}</label>
            {{field}}

          </div>
          {% endfor %}
          <button class="btn btn-primary btn-block">Criar</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

mbank/mbank/http_face/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block sourcefiles %}
  <!-- Page level plugin CSS-->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
  <!-- Custom styles for dashboard template-->
  <link href="{% static 'admin_template/css/sb-admin.css' %}" rel="stylesheet">
{% endblock %}

{% block sidebar %}
  <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <!--
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Minha Conta">
          <a class="nav-link" href="#">
            <i class="fa fa-fw fa-user"></i>
            <span class="nav-link-text">Minha Conta</span>
          </a>
        </li>
        -->
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Contas Bancárias">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-bank"></i>
            <span class="nav-link-text">Contas</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseComponents">
            {% for account in accounts %}
            <li>
              <a href="{% url 'http_face:account_details' account.get_uuid%}">
              <i class="fa fa-fw fa-eye"></i>
              {{ account.get_account_number }}</a>
            </li>
            {% endfor %}
            <li>
              <a href="{% url 'http_face:add_account' %}">
              <i class="fa fa-fw fa-plus"></i>
              Criar Conta</a>
            </li>
          </ul>
        </li>

      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
  {% endblock %}

{% block content %}


{% endblock %}


{% block sourcefiles_end %}
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'admin_template/js/sb-admin.min.js' %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static 'admin_template/js/sb-admin-datatables.min.js' %}"></script>
    <script src="{% static 'admin_template/js/sb-admin-charts.min.js' %}"></script>

{% endblock %}

mbank/mbank/http_face/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="mt-5">Pequeno Sistema Bancario</h1>
          <p class="lead">Seja um cliente da mais incrivel agência bancária</p>
        </div>
      </div>
    </div>

{% endblock %}

mbank/mbank/http_face/templates/login.html
{% extends 'base.html' %}

{% block content %}
<style>
.form-group input {
    display: block;
    width: 100%;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-image: none;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }

</style>
  <div class="container">
    <div class="col-sm-6 mx-auto">
      <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          {{ form.non_field_errors }}

          {% for field in form %}
          <div class="form-group">

            <label>{{field.label}}</label>
            {{field}}

          </div>
          {% endfor %}
          <button class="btn btn-primary btn-block">Login</button>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="{% url 'http_face:register' %}">Registre-se</a>
        </div>
      </div>
    </div>
  </div>
    </div>

{% endblock %}

mbank/mbank/http_face/templates/register.html
{% extends 'base.html' %}

{% block content %}
<style>
.form-group input {
    display: block;
    width: 100%;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-image: none;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }

</style>
  <div class="container">
    <div class="col-sm-6  mx-auto">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          {{ form.non_field_errors }}

          {% for field in form %}
          <div class="form-group">

            <label>{{field.label}}</label>
            {{field}}

          </div>
          {% endfor %}
          <button class="btn btn-primary btn-block">Salvar</button>
        </form>
        <div class="text-center">
          <!--<a class="d-block small mt-3" href="http_face:register">Registre-se</a>-->
        </div>
      </div>
    </div>
  </div>
    </div>

{% endblock %}